//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unagi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unagi.Lang_en_US", typeof(Lang_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report and delete .
        /// </summary>
        internal static string btnReportDel {
            get {
                return ResourceManager.GetString("btnReportDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string btnReportNoDel {
            get {
                return ResourceManager.GetString("btnReportNoDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send report. Please call the servicedesk for assistance..
        /// </summary>
        internal static string errFailSent {
            get {
                return ResourceManager.GetString("errFailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read App.config or one of it sections; using defaults.
        /// </summary>
        internal static string errNoAppConfig {
            get {
                return ResourceManager.GetString("errNoAppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an eMail before pressing the report button..
        /// </summary>
        internal static string errNoSelection {
            get {
                return ResourceManager.GetString("errNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only report one eMail at a time. Select and press the button once for each eMail..
        /// </summary>
        internal static string errOnlyOne {
            get {
                return ResourceManager.GetString("errOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been reported.
        /// </summary>
        internal static string msgConfirmReport {
            get {
                return ResourceManager.GetString("msgConfirmReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;[D]\[U]&quot; made a report to possible phishing.
        ///This should be investigated..
        /// </summary>
        internal static string rptBody {
            get {
                return ResourceManager.GetString("rptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report phishing.
        /// </summary>
        internal static string rptBtnGroup {
            get {
                return ResourceManager.GetString("rptBtnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phishing report.
        /// </summary>
        internal static string rptSubject {
            get {
                return ResourceManager.GetString("rptSubject", resourceCulture);
            }
        }
    }
}
